#!/bin/bash

if [ -f ./.env ];
then
  . ./.env
elif [ -f $HOME/.env.boot-dev ];
then
  . $HOME/.env.boot-dev
else
  echo "ERROR: No .env file exists."
  exit 1
fi

if [ ! -v USERNAME ]; then
  echo "ERROR: Environment variable USERNAME does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

if [ ! -v GIT_UTILS_REPO ]; then
  echo "ERROR: Environment variable GIT_UTILS_REPO does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

if [ ! -v GIT_UTILS_REPO_RAW ]; then
  echo "ERROR: Environment variable GIT_UTILS_REPO_RAW does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

if [ ! -v GIT_BEARER_TOKEN ]; then
  echo "ERROR: Environment variable GIT_BEARER_TOKEN does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

if [ ! -v GIT_USER_NAME ]; then
  echo "ERROR: Environment variable GIT_USER_NAME does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

if [ ! -v GIT_USER_EMAIL ]; then
  echo "ERROR: Environment variable GIT_USER_EMAIL does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

if [ ! -v HOME_NIX ]; then
  echo "ERROR: Environment variable HOME_NIX does not have a value."
  echo "Review .env.README for .env file format."
  exit 2
fi

export LOCAL_DIRECTORY="$HOME/container-host"
mkdir -p $LOCAL_DIRECTORY

PODMAN=$(which podman)

if [ -f PODMAN ];
then
 podman compose build --no-cache
else
 docker compose --no-cache build
fi

