#!/bin/bash

export LOCAL_DIRECTORY="$HOME/container-host"

DOCKER=$(which docker)
DOCKER_COMPOSE=$(which docker-compose)

if [ -f $DOCKER_COMPOSE ]; then
  $DOCKER_COMPOSE up
else
  $DOCKER compose up
fi
