#!/bin/bash

source .env

export LOCAL_DIRECTORY

DOCKER_COMPOSE=$(which docker-compose)
if [ $? -ne 0 ]; then
  DOCKER_COMPOSE=""
fi

PODMAN=$(which docker)
if [ $? -ne 0 ]; then
  PODMAN=""
fi

DOCKER=$(which docker)
if [ $? -ne 0 ]; then
  DOCKER=""
fi

if [ -f "$DOCKER_COMPOSE" ]; then
  $DOCKER_COMPOSE up -d
else
  if [ -f "$PODMAN" ]; then
    $PODMAN compose up -d
  else
    $DOCKER compose up -d
  fi
fi
